### ISSUE TITLE
Blocked on 5% "opening link.."

### ISSUE THREAD

**Issue by simon-silvestre** [0xSpoofed/Vingod#1]
items not found

**Comment by simon-silvestre** [comment]
hello thanks you for your awnser but firefox open when i put in argument line 417 but it say item not found anyways. I see the articles on firefox but it say item not found

**Comment by 0xSpoofed** [comment]
Hello, 
I just retested the Vingod version, the same error returned to me, so the error comes from the script, I will work on it shortly. Excuse me inconvenience, a committee will soon be made to correct the problem. 
Thank you and have a good day.

**Comment by simon-silvestre** [comment]
Thanks you very much I really appreciate your work. I will try to find the error too, so if I find it, I will notify you. Have a good day too ;)

**Comment by 0xSpoofed** [comment]
Hello, 
I just pushed an intermediate comit to partially solve the problem. Items are now sent correctly but images do not appear. I will solve the problem in a future comit. 
Thanks for your help, 
Have a good day ;)
