### ISSUE TITLE
issue to start the bot

### ISSUE THREAD

**Issue by w20000** [0xSpoofed/Vingod#2]
hello men , when i type 1 to start the bot its say "5% opening link" then its stop to say "An error has occurred, please check settings and retry...."  . Please help me

**Comment by 0xSpoofed** [comment]
Hello, excuse me for the error, I just tested from my side, an error occurs too. So I'm going to update the bot. I will let you know when it is updated. Also know that a new version is under development. Have a nice day. Adapters

**Comment by 0xSpoofed** [comment]
Hello again, I just made a correction to the script that now works normally, the problem came from a small change in the vinted site. I hope this will help you. If this is not the case do not hesitate to contact me on discord: 4dapt3rs or to reopen an issue. Have a nice day. Adapters
