### ISSUE TITLE
Brand id error

### ISSUE THREAD

**Issue by jvstlele** [0xSpoofed/Vingod#3]
Hi, I have problem when I enter the brand id, even if I enter for example "Nike" it tells me that I have to enter a correct one, could you help me please?

**Comment by jvstlele** [comment]
and when I try to enter the id taken from the vintedi search bar it says "No items found :/"

**Comment by 0xSpoofed** [comment]
Sorry for the inconvenience, this is in fact a redesign of the link system by Vinted, a new bot update is required, I'll take care of it as soon as possible. Have a nice day.
